name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npx nypm@latest i

      - name: Build
        run: npm run build

      # creates release and adds audio-player-vue.zip. as asset
      - run: npx changelogithub --assets ./packages/cli/dist/mapbox-embed-vue.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
